FROM node:18.16.1 AS build
LABEL maintainer="pmarchel47@gmail.com"
WORKDIR /frontend
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:18.16.1
RUN npm install -g serve
COPY --from=build /frontend/build /frontend
EXPOSE 4000
CMD serve -s /frontend -l 4000