version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: react-express-frontend-prod
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - 3001:3001
    container_name: react-express-server-prod
