version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - 4000:4000
    container_name: react-express-frontend
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - 5000:5000
    container_name: react-express-server
